[package]
name = "dsp"
version = "0.1.0"
authors = ["탁동혁 <tdh8316@naver.com>"]
edition = "2018"

[dependencies]
clap = { git = "https://github.com/clap-rs/clap", tag = "v2.33.0" }
either = "1.5.3"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "llvm10-0" }
num-bigint = "0.2"
num-complex = { version = "0.2", features = ["serde"] }
num-traits = "0.2"
rustpython-parser = { git = "https://github.com/RustPython/RustPython" }

